"""Write every voice command to commands.txt.

Generated from `plugin.manifest()` — the same declaration the fast router
compiles into patterns and that M2 will hand the LLM as its tool schema. A
hand-written list would drift the first time a command was added and nobody
would notice until someone spoke to it and nothing happened.

    .venv/bin/python scripts/dump_commands.py            # -> commands.txt
    .venv/bin/python scripts/dump_commands.py --stdout
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from aia.core.config import CONFIG  # noqa: E402
from aia.plugins.base import Registry  # noqa: E402
from aia.plugins.kodama import KodamaLite  # noqa: E402
from aia.plugins.system import System  # noqa: E402

OUT = Path(__file__).resolve().parents[1] / "commands.txt"
RULE = "=" * 74


def render() -> str:
    registry = Registry([KodamaLite(), System()])
    wake = CONFIG.wake

    out: list[str] = []
    add = out.append

    add(RULE)
    add("AIA — voice commands")
    add(RULE)
    add("")
    add(f"Wake word: {wake.phrase}")
    add("")
    add("Say the wake word, then the command — either in one breath")
    add(f'("{wake.phrase}播放五月天") or with a pause after it.')
    add("")
    add("Phrases are matched by SOUND, not spelling, so they do not have to be")
    add("hit exactly: 不放歌曲 still reaches `resume`, and 下一手 reaches `next`.")
    add("Anything not recognised as a command is repeated back.")
    add("")
    add("<...> marks a free-text argument. It always runs to the end of the")
    add("sentence, because speech has no reliable way to mark where it stops.")
    add("")

    for plugin in registry.plugins:
        add(RULE)
        add(f"{plugin.name.upper()} — {plugin.description}")
        add(RULE)
        for command in plugin.commands():
            notes = []
            if command.confirm:
                notes.append("ASKS FOR CONFIRMATION")
            if command.stops_playback:
                notes.append("leaves audio stopped")
            argument = f"  <{'/'.join(command.params)}>" if command.params else ""
            add("")
            add(f"  {command.name}{argument}"
                + (f"   [{', '.join(notes)}]" if notes else ""))
            add(f"    {command.description}")
            for code, label in (("en", "English"), ("zh", "中文   ")):
                phrases = command.phrases.get(code, ())
                if phrases:
                    add(f"      {label} : " + "  |  ".join(phrases))
        add("")

    add(RULE)
    add("CONFIRMATION")
    add(RULE)
    add("")
    add("Commands marked ASKS FOR CONFIRMATION say what they are about to do")
    add("and then keep listening — no wake word needed for the answer.")
    add("")
    add("  yes : 确定 · 是 · 是的 · 对 · 好 · 好的 · 可以 · 没错 · yes · sure · ok")
    add("  no  : 取消 · 不 · 不要 · 别 · 算了 · 不用 · no · cancel · never mind")
    add("")
    add("Silence, or anything that is neither, cancels. For something")
    add("irreversible, 'I could not tell' has to mean no.")
    add("")
    add(RULE)
    add(f"{sum(len(p.commands()) for p in registry.plugins)} commands. "
        "Generated by scripts/dump_commands.py — do not edit by hand.")
    add(RULE)
    return "\n".join(out) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--stdout", action="store_true")
    args = parser.parse_args()

    logging.basicConfig(level=logging.ERROR)
    text = render()
    if args.stdout:
        sys.stdout.write(text)
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
